package com.section.shiori.ui.theme

import androidx.compose.ui.graphics.Color

// Seed: #0061A4 (blue). Tonal palette values below follow the Material 3 baseline
// generated from that seed.
val BluePrimaryLight = Color(0xFF0061A4)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD1E4FF)
val BlueOnPrimaryContainerLight = Color(0xFF001D36)
val BlueSecondaryLight = Color(0xFF535F70)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFD7E3F7)
val BlueOnSecondaryContainerLight = Color(0xFF101C2B)
val BlueTertiaryLight = Color(0xFF6B5778)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFF2DAFF)
val BlueOnTertiaryContainerLight = Color(0xFF251431)
val BlueErrorLight = Color(0xFFBA1A1A)
val BlueOnErrorLight = Color(0xFFFFFFFF)
val BlueErrorContainerLight = Color(0xFFFFDAD6)
val BlueOnErrorContainerLight = Color(0xFF410002)
val BlueBackgroundLight = Color(0xFFFDFCFF)
val BlueOnBackgroundLight = Color(0xFF1A1C1E)
val BlueSurfaceLight = Color(0xFFFDFCFF)
val BlueOnSurfaceLight = Color(0xFF1A1C1E)
val BlueSurfaceVariantLight = Color(0xFFDFE2EB)
val BlueOnSurfaceVariantLight = Color(0xFF43474E)
val BlueOutlineLight = Color(0xFF73777F)
val BlueOutlineVariantLight = Color(0xFFC3C7CF)
val BlueInverseSurfaceLight = Color(0xFF2F3033)
val BlueInverseOnSurfaceLight = Color(0xFFF1F0F4)
val BlueInversePrimaryLight = Color(0xFF9ECAFF)
val BlueSurfaceDimLight = Color(0xFFDBD9DD)
val BlueSurfaceBrightLight = Color(0xFFFDFCFF)
val BlueSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val BlueSurfaceContainerLowLight = Color(0xFFF7F9FF)
val BlueSurfaceContainerLight = Color(0xFFEFEDF1)
val BlueSurfaceContainerHighLight = Color(0xFFE9E7EB)
val BlueSurfaceContainerHighestLight = Color(0xFFE3E2E6)

val BluePrimaryDark = Color(0xFF9ECAFF)
val BlueOnPrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFFD1E4FF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val BlueOnSecondaryDark = Color(0xFF253140)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val BlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD6BEE4)
val BlueOnTertiaryDark = Color(0xFF3B2948)
val BlueTertiaryContainerDark = Color(0xFF523F5F)
val BlueOnTertiaryContainerDark = Color(0xFFF2DAFF)
val BlueErrorDark = Color(0xFFFFB4AB)
val BlueOnErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val BlueOnErrorContainerDark = Color(0xFFFFDAD6)
val BlueBackgroundDark = Color(0xFF1A1C1E)
val BlueOnBackgroundDark = Color(0xFFE2E2E6)
val BlueSurfaceDark = Color(0xFF1A1C1E)
val BlueOnSurfaceDark = Color(0xFFE2E2E6)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val BlueOnSurfaceVariantDark = Color(0xFFC3C7CF)
val BlueOutlineDark = Color(0xFF8D9199)
val BlueOutlineVariantDark = Color(0xFF43474E)
val BlueInverseSurfaceDark = Color(0xFFE2E2E6)
val BlueInverseOnSurfaceDark = Color(0xFF1A1C1E)
val BlueInversePrimaryDark = Color(0xFF0061A4)
val BlueSurfaceDimDark = Color(0xFF111416)
val BlueSurfaceBrightDark = Color(0xFF37393C)
val BlueSurfaceContainerLowestDark = Color(0xFF0C0E11)
val BlueSurfaceContainerLowDark = Color(0xFF1A1C1E)
val BlueSurfaceContainerDark = Color(0xFF1E2022)
val BlueSurfaceContainerHighDark = Color(0xFF282A2D)
val BlueSurfaceContainerHighestDark = Color(0xFF333538)

val StatusWatching = Color(0xFF4CAF50)
val StatusCompleted = Color(0xFF2196F3)
val StatusPlanned = Color(0xFF9E9E9E)
val StatusDropped = Color(0xFFF44336)
val StatusOnHold = Color(0xFFFBC02D)
